### ISSUE TITLE
Default content type and views not available

### ISSUE THREAD

**Issue by pgrayove-mcpl** [backdrop-contrib/recipe#3]
After I installed this to test, the default "recipe" content type isn't created and the recipe views aren't created as part of the install. When I use the Recipe Import tab under add content and try to add a recipe exported from D7 in MasterCook 4 format, I get the following notices when I click the preview:

`Could not find the ingredient units in * Exported from MasterCook * (Recipe By : Adapted from Bernard Clayton's New Complete Book of Breads by Bernard Clayton, Jr. )
    Could not find the ingredient units in * Exported from MasterCook * (Serving Size : 1 Preparation Time :0:20 )
    Could not find the ingredient units in * Exported from MasterCook * (Categories : )`

Once imported, there's no content added except the title.  Probably because the recipe content type wasn't created.

**Comment by argiepiano** [comment]
I'm looking at the installation of default content type, but it's working fine on my end. I just installed it (from scratch) in a Demo Sandbox. Can you please check it out?

https://latest-h91pizo3cldhfd7gdn0a1uoyictdpgbs.tugboatqa.com/

The username is "admin" and the password "password". The module is installed there (I haven't tested the second part of your issue).

I don't know how you installed it in your local. To test in your local be sure you download the module from:
https://github.com/backdrop-contrib/recipe/archive/refs/heads/1.x-1.x.zip

This will download the latest version.

<img width="811" alt="Screen Shot 2023-04-24 at 8 53 28 AM" src="https://user-images.githubusercontent.com/9938978/234034401-fefcee38-6649-4062-9b2d-73df0923965c.png">

**Comment by pgrayove-mcpl** [comment]
I definitely was not seeing that.  Looks like I wasn't getting a clean install after trying some previous code_upgrade versions.  I'll try again on a clean site.

**Comment by pgrayove-mcpl** [comment]
I got it installed. It looks like everything is there now, including the views.  I need to add some test recipes to fully test, but looks like this was just a botched install on my part.  Sorry about that.

**Comment by argiepiano** [comment]
Glad it worked! Thanks for testing. If you feel this issue is resolved, please close it :)

**Comment by pgrayove-mcpl** [comment]
Looks like there might be some repeated fields (ingredients, cooking time, preparation time) in the recipe content type, but I'm going to close this issue as the content type and views are there. I'll test more and report any specific issues I find.
