### ISSUE TITLE
Recipe node type array to string conversion

### ISSUE THREAD

**Issue by pgrayove-mcpl** [backdrop-contrib/recipe#4]
There are a few places where I am getting notices about array to string conversion and any text entered in those fields isn't getting saved.

- `Notice: Array to string conversion in theme_recipe_instructions() (line 940 of /app/web/modules/recipe-1.x-1.x/recipe.module).`
Line 940: `$output .= '<div class="section">' . $node->recipe_instructions . '</div>';`

- `Notice: Array to string conversion in theme_recipe_description() (line 904 of /app/web/modules/recipe-1.x-1.x/recipe.module).`
Line 904: `$output .= '<div class="section">' . $node->recipe_description . '</div>';`

"Additional notes" and "Source" text fields are also not getting saved, but there are no notices for those.

**Comment by argiepiano** [comment]
Thanks. Did you have a chance to figure out what's causing this?

**Comment by argiepiano** [comment]
I'm not able to reproduce this problem in my testing. This may have been related to the issue you closed earlier with the duplicate fields. Let me know if you have additional steps to generate the warning.

**Comment by pgrayove-mcpl** [comment]
This was definitely because of the leftover json settings files from the previous install of the module.  It works fine now.
